### PR TITLE
Pl add test report

### PR DESCRIPTION
**Pull request by paulflang**
At the COMBINE conference I got the feedback that we should make the SBML test suite results public. So I am adding them with this PR. Not nicely automated yet, as the results come from an unmerged branch of the [SBMLBioModelsRepository.jl](https://github.com/anandijain/SBMLBioModelsRepository.jl/tree/pl-testing2/src) (AFAIK he main branch does not output correctness of the simulation results).

### CODE REVIEW

**Comment by anandijain** [comment]
I think it'd be better to just have a tracker issue reporting the results, rather than storing a CSV in the repo itself. 

This is how the rest of sciml handles images/assets in readmes (they just link to uploaded files in issues).

**Comment by paulflang** [comment]
sounds good to me. can you create the issue and link the file the way you think is best?

**Comment by anandijain** [comment]
cool https://github.com/SciML/SBMLToolkit.jl/issues/45 should be sufficient. 
if you want we can link to this in the readme, but i think it should be fine as is

**Comment by paulflang** [comment]
Thanks Anand, the results tracker looks great. But I did link it in the README to help our users finding it.

**Pull request closed without merging**
